
<section class="welcome">
<section align="center">
<br><button type="button"><a href="adduser">Inscription </a></button>
</section>
<section align="center">
<br><button type="button"><a href="login">Log-in </a></button>
</section>
<section align="center">
<br><button type="button"><a href="meal">Menu for the day</a></button>
</section>
<section align="center">
<br><button type="button"><a href="meals">Our Menu</a></button>
</section>
<section align="center">
<br><button type="button"><a href="about">Reservation</a></button>
</section>
</section>



<?= $message ?>
