  <form action="adduser" method="post">
    <fieldset>
      <legend> Not yet a member? </legend>
      <div class="container">
        <label for="nom"><strong>Family Name</strong></label>
        <input type="text" placeholder="Family Name" name="nom" required>

        <label for="prenom"><strong>First Name</strong></label>
        <input type="text" placeholder="First Name" name="prenom" required>

        <label for="pseudo"><strong>NickName</strong></label>
        <input type="text" placeholder="NickName" name="pseudo" required>

        <label for="email"><strong>E-mail</strong></label>
        <input type="text" placeholder="Enter Email" name="email" required>

        <label for="psw"><strong>Password</strong></label>
        <input type="password" placeholder="Enter Password" name="password" required>

        <button type="submit">Sign-up</button>

      </div>
    </fieldset>
 </form>
