
<div align="center">

  <h3><i class="fas fa-heart"></i> <span style="text-decoration: underline; color:green"><?= $carte['categorie'] ?></span><i class="fas fa-heart"></i></h3>
  <img src="<?= $wwwUrl ?>/images/meals/<?= $carte['photo'] ?>" alt="<?= $carte['nom'] ?>" />
    <p> <strong><?= $carte['nom'] ?></strong></p>
    <p>prix: <?= $carte['prix'] ?> <strong>$</strong></p>
    <p>en stock: <strong><?= $carte['stock'] ?></strong></p>
    <p>disponible sur place: <strong><?= $carte['disponible_sur_place'] ?></strong></p>
    <p><?= $carte['description'] ?></p>
