<!-- Message de notification -->

<!-- Code HTML à écrire -->
<fieldset>
  <legend> Not yet a member? </legend>
  <form action=" " method="post">
      <div class="container">
        <label for="nom"><strong>Family Name</strong></label>
        <input type="text" placeholder="Family Name" name="nom" required>

        <label for="prenom"><strong>First Name</strong></label>
        <input type="text" placeholder="First Name" name="prenom" required>

        <label for="pseudo"><strong>NickName</strong></label>
        <input type="text" placeholder="NickName" name="pseudo" required>

        <label for="email"><strong>E-mail</strong></label>
        <input type="text" placeholder="Enter Email" name="email" required>

        <label for="psw"><strong>Password</strong></label>
        <input type="password" placeholder="Enter Password" name="password" required>

        <button type="submit">Register</button>

      </div>
 </form>
</fieldset>

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
    </tbody>
</table>
